server:
  port: 8085

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: http://localhost:8082/realms/atum
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            clientId: admin-server
            clientSecret: Da4WFWZ1gEWJgNRSGhDcAHWKNFdzI1eG
            scope:
              - metrics
          login:
            provider: keycloak
            clientId: admin-server
            clientSecret: Da4WFWZ1gEWJgNRSGhDcAHWKNFdzI1eG
            scope:
              - openid
              - metrics

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/atum

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

