server:
  port: 8085

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/atum
        registration:
          keycloak:
            authorizationGrantType: client_credentials
            clientId: admin-server
            clientSecret: ${ADMIN_SERVER_CLIENT_SECRET}
            scope:
              - metrics
          login:
            provider: keycloak
            clientId: admin-server
            clientSecret: ${ADMIN_SERVER_CLIENT_SECRET}
            scope:
              - openid
              - metrics

      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/atum

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

