name: atum

services:

  # Инфраструктура
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
      - '8082:8080'
    command: start-dev --import-realm
    networks:
      - atum-network

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.93.12
    command: -promscrape.config=/promscrape.yaml
    volumes:
      - './config/victoria-metrics/promscrape_docker_compose.yaml:/promscrape.yaml'
    ports:
      - '8428:8428'
    networks:
      - atum-network

  catalogue-db:
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: glhf5561783742
      POSTGRES_DB: products_catalogue_database
    networks:
      - atum-network


  feedback-db:
    image: mongo:7
    ports:
      - '27017:27017'
    networks:
      - atum-network

  admin-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: admin-server/target/admin-server-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8085:8085'
    depends_on:
      - keycloak
    networks:
      - atum-network

  catalogue-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: catalogue-service/target/catalogue-service-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - catalogue-db
      - keycloak
    networks:
      - atum-network

  feedback-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: feedback-service/target/feedback-service-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - feedback-db
      - keycloak
    networks:
      - atum-network

  customer-application:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: customer-application/target/customer-application-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - feedback-service
    networks:
      - atum-network

  manager-application:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: manager-application/target/manager-application-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - catalogue-service
    networks:
      - atum-network

networks:
  atum-network:
    driver: bridge