name: atum

services:

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    env_file:
      - .env
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
      - '8082:8080'
    command: start-dev --import-realm
    networks:
      - atum-network

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.93.12
    command: -promscrape.config=/promscrape.yaml
    env_file:
      - .env
    volumes:
      - './config/victoria-metrics/promscrape_docker_compose.yaml:/promscrape.yaml'
    ports:
      - '8428:8428'
    networks:
      - atum-network

  catalogue-db:
    image: postgres:16
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - atum-network

  feedback-db:
    image: mongo:7
    env_file:
      - .env
    ports:
      - '27017:27017'
    networks:
      - atum-network

  admin-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: admin-server/target/admin-server-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ADMIN_SERVER_CLIENT_SECRET: ${ADMIN_SERVER_CLIENT_SECRET}
    env_file:
      - .env
    ports:
      - '8085:8085'
    depends_on:
      - keycloak
    networks:
      - atum-network

  catalogue-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: catalogue-service/target/catalogue-service-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CATALOGUE_SERVICE_CLIENT_SECRET: ${CATALOGUE_SERVICE_CLIENT_SECRET}
      CATALOGUE_SERVICE_DB_PASSWORD: ${CATALOGUE_SERVICE_DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - catalogue-db
      - keycloak
    networks:
      - atum-network

  feedback-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: feedback-service/target/feedback-service-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      FEEDBACK_SERVICE_CLIENT_SECRET: ${FEEDBACK_SERVICE_CLIENT_SECRET}
    env_file:
      - .env
    depends_on:
      - feedback-db
      - keycloak
    networks:
      - atum-network

  customer-application:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: customer-application/target/customer-application-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CUSTOMER_APPLICATION_CLIENT_SECRET: ${CUSTOMER_APPLICATION_CLIENT_SECRET}
      CUSTOMER_APPLICATION_METRICS_CLIENT_SECRET: ${CUSTOMER_APPLICATION_METRICS_CLIENT_SECRET}
    env_file:
      - .env
    depends_on:
      - feedback-service
    networks:
      - atum-network

  manager-application:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: manager-application/target/manager-application-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MANAGER_APPLICATION_CLIENT_SECRET: ${MANAGER_APPLICATION_CLIENT_SECRET}
      MANAGER_APPLICATION_METRICS_CLIENT_SECRET: ${MANAGER_APPLICATION_METRICS_CLIENT_SECRET}
      MANAGER_APPLICATION_DB_PASSWORD: ${MANAGER_APPLICATION_DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - catalogue-service
    networks:
      - atum-network

networks:
  atum-network:
    driver: bridge
