name: atum

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    env_file:
      - .env
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    ports:
      - '8082:8080'
    command:
      - start
      - --import-realm
    networks:
      - atum-network

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.93.12
    command: -promscrape.config=/promscrape.yaml
    env_file:
      - .env
    volumes:
      - './config/victoria-metrics/promscrape_docker_compose.yaml:/promscrape.yaml'
    ports:
      - '8428:8428'
    networks:
      - atum-network

  catalogue-db:
    image: postgres:16
    ports:
      - '5433:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "!rT8v^Q2m#L5z@J9p*X3w&hF7"
      POSTGRES_DB: products_catalogue_database
    networks:
      - atum-network

  feedback-db:
    image: mongo:7
    env_file:
      - .env
    ports:
      - '27017:27017'
    networks:
      - atum-network

  admin-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: admin-server/target/admin-server-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ADMIN_SERVER_CLIENT_SECRET: Xh6RPIBbr4bGiVkdtDFhIoSmxCob1XrD
    env_file:
      - .env
    ports:
      - '8085:8085'
    depends_on:
      - keycloak
    networks:
      - atum-network

  catalogue-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: catalogue-service/target/catalogue-service-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CATALOGUE_SERVICE_CLIENT_SECRET: u34hkHPpwGWwx29mYcVr6g2BgySEQGts
      POSTGRES_PASSWORD: "!rT8v^Q2m#L5z@J9p*X3w&hF7"
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - catalogue-db
      - keycloak
    networks:
      - atum-network

  feedback-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: feedback-service/target/feedback-service-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      FEEDBACK_SERVICE_CLIENT_SECRET: 2s0iVksCTI7VvYJBZo2Y4aHiuvtCgJFx
    env_file:
      - .env
    ports:
      - '8083:8083'
    depends_on:
      - feedback-db
      - keycloak
    networks:
      - atum-network

  customer-application:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: customer-application/target/customer-application-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CUSTOMER_APPLICATION_CLIENT_SECRET: 1gaU2P582s1NSl0SRNAtYeDX6ZB9nDvO
      CUSTOMER_APPLICATION_METRICS_CLIENT_SECRET: jrGLZAkIEUn5zv5c2IiHl987pbwmZzpd
    env_file:
      - .env
    ports:
      - '8084:8084'
    depends_on:
      - feedback-service
    networks:
      - atum-network

  manager-application:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: manager-application/target/manager-application-25.1.1-SNAPSHOT-exec.jar
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MANAGER_APPLICATION_CLIENT_SECRET: EyPPKE2KC0WTFmLUby2ruW5UCLloZC8d
      MANAGER_APPLICATION_METRICS_CLIENT_SECRET: iYMiAQyonRMMBIv5UEpLBvbYDJyHSpHg
      MANAGER_APPLICATION_DB_PASSWORD: "!rT8v^Q2m#L5z@J9p*X3w&hF7"
    env_file:
      - .env
    ports:
      - '8081:8081'
    depends_on:
      - catalogue-service
    networks:
      - atum-network

networks:
  atum-network:
    driver: bridge
