name: atum
services:

  # Postgresql
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: products_catalogue_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "!rT8v^Q2m#L5z@J9p*X3w&hF7"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atum-network

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL: jdbc:postgresql://postgres:5432/products_catalogue_database
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: "!rT8v^Q2m#L5z@J9p*X3w&hF7"
    ports:
      - "8082:8080"
    volumes:
      - './config/keycloak/import:/opt/keycloak/data/import'
    command: start-dev --import-realm
    networks:
      - atum-network

  # Catalogue Service
  catalogue-service:
    build:
      context: ./catalogue-service
      dockerfile: Dockerfile
    container_name: catalogue-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products_catalogue_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "!rT8v^Q2m#L5z@J9p*X3w&hF7"
      DB_SCHEMA: catalogue
    networks:
      - atum-network

  # Manager Application
  manager-application:
    build:
      context: ./manager-application
      dockerfile: Dockerfile
    container_name: manager-application
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products_catalogue_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "!rT8v^Q2m#L5z@J9p*X3w&hF7"
      DB_SCHEMA: user_management
    networks:
      - atum-network

networks:
  atum-network:
    driver: bridge

volumes:
  postgres_data:
