server:
  port: 8084

spring:

  application:
    name: customer-application

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: customer-application
          service-host-type: ip
        url: http://localhost:8085

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: http://localhost:8082/realms/atum
            userNameAttribute: preferred_username
        registration:
          keycloak:
            clientId: customer-application
            clientSecret: 1gaU2P582s1NSl0SRNAtYeDX6ZB9nDvO
            authorizationGrantType: authorization_code
            scope:
              - openid
              - microprofile-jwt
              - view_catalogue
          metrics:
            provider: keycloak
            authorizationGrantType: client_credentials
            clientId: customer-application-metrics-client
            clientSecret: jrGLZAkIEUn5zv5c2IiHl987pbwmZzpd
            scope:
              - metrics_server

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/atum
atum:
  services:
    catalogue:
      uri: http://localhost:8080
    feedback:
      uri: http://localhost:8083
    reviews:
      uri: http://localhost:8083

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'