apiVersion: apps/v1
kind: Deployment
metadata:
  name: atum-config-server
spec:
  selector:

  template:
    spec:
      containers:
        - name: atum-config-server
          image: localhost:5000/atum/config-server:25.1.1
          ports:
            - containerPort: 8888
              