server:
  port: 8081

logging:
  level:
    sql: info
    org.springframework.security: debug

spring:
  application:
    name: manager-application

  boot:
    admin:
      client:
        enabled: true
        instance:
          name: manager-application
          service-host-type: ip
        url: http://admin-server:8085

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/atum
            userNameAttribute: preferred_username
        registration:
          keycloak:
            clientId: manager-application
            clientSecret: jlimO5DTqWPZgtN3eNRSALgEHWXBMTcx
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - microprofile-jwt
              - view_catalogue
              - edit_catalogue
          metrics:
            provider: keycloak
            authorizationGrantType: client_credentials
            clientId: manager-application-metrics-client
            clientSecret: dSSmH2Pa0VaiBEwl6p3um6JjsGHjchoC
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/atum

  datasource:
    url: jdbc:postgresql://catalogue-db:5432/products_catalogue_database
    username: postgres
    password: "!rT8v^Q2m#L5z@J9p*X3w&hF7"

  flyway:
    schemas:
      - user_management

catalogue:
  service:
    base:
      uri: http://catalogue-service:8080
    registration-id: keycloak

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
