server:
  port: 8081

logging:
  level:
    sql: info
    org.springframework.security: debug

spring:
  application:
    name: manager-application

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: http://keycloak:8080/realms/atum
            userNameAttribute: preferred_username
        registration:
          keycloak:
            clientId: manager-application
            clientSecret: EyPPKE2KC0WTFmLUby2ruW5UCLloZC8d
            authorizationGrantType: authorization_code
            redirect-uri: http://manager-application:8081/login/oauth2/code/keycloak
            scope:
              - openid
              - microprofile-jwt
              - view_catalogue
              - edit_catalogue

  datasource:
    url: jdbc:postgresql://postgres:5432/products_catalogue_database
    username: postgres
    password: "!rT8v^Q2m#L5z@J9p*X3w&hF7"

  flyway:
    schemas:
      - user_management

catalogue:
  service:
    base:
      uri: http://catalogue-service:8080
    registration-id: keycloak
