server:
  port: 8080

spring:
  application:
    name: catalogue-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: false
      uri:
        - http://localhost:8888