server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
            search-locations:
              - file:///D:/git/atum/config/cloud/{application}/{profile}