server:
  port: 8083
spring:
  application:
    name: feedback-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/feedback-service-database
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/atum
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true